### ISSUE TITLE
inconsistent results vs vim.lsp.buf.code_action()

### ISSUE THREAD

**Issue by atinylittleshell** [luckasRanarison/clear-action.nvim#17]
I'm using vtsls for typescript files (tried other lsp like typescript-tools instead of vtsls as well but get same result) and I noticed that in many places when using clear-action's code_action I get "no code action available" but when I use vim.lsp.buf.code_action() I can get several options. What can I do or provide to debug what's causing this inconsistency?

**Comment by luckasRanarison** [comment]
Hi, sorry for the late reply. Could you check if it's fixed now? The inconsistencies may be related to the diagnostics sent to the server, that issue was fixed with b89ae9dc5da8fba43e4fc2805202c763cd5bb3fd.

**Comment by atinylittleshell** [comment]
works now! thanks for the fix!
