### ISSUE TITLE
[feat]: If it is possible to provide API or user commands that can use directly

### ISSUE THREAD

**Issue by shellRaining** [luckasRanarison/clear-action.nvim#19]
Thank you for writing this plugin. I like it very much, but there are some inconveniences when using it. For example, I want to write the key mapping myself, but there is no corresponding API. Can you provide it or expose some usercmd?

**Comment by luckasRanarison** [comment]
Sorry, I'm not sure to completely understand your request, what mapping are you talking about?

**Comment by shellRaining** [comment]
<img width="1160" alt="image" src="https://github.com/luckasRanarison/clear-action.nvim/assets/111564053/50e609ec-7cc5-4512-9f69-722e6065fcf7">

just show in the below window, like this form

```lua
{
    mode = { "n" },
    lhs = "<leader>ca",
    rhs = "<cmd>ClearCodeAction<CR>", -- just a Usercmd
    options = { silent = true },
    description = "clear code action",
},
```

**Comment by luckasRanarison** [comment]
You can now have more control on the keymaps with the following format:
```lua
{
  key = "<leader>aq",
  mode = { "n" }, -- defaults to n, v
  options = { -- it's the last argument of `vim.keymap.set()`
    desc = "Quickfix",
    silent = true, -- defaults to true
}
```
