### ISSUE TITLE
Popup doesn't work when the code action has a multi-line string

### ISSUE THREAD

**Issue by Ciel-MC** [luckasRanarison/clear-action.nvim#20]
I looked into it a little bit and it's caused by buf_set_line not accepting multiline strings, I tried to fix it by just breaking it into multiple lines, it doesn't open an empty window then at least, but it caused more issues like incorrect formatting(italics and colors) and incorrect window size, so I gave up trying to make a trivial fix :p

**Comment by luckasRanarison** [comment]
Fixed it by substituting the linebreaks to string literals, it might not look great but I couldn't find a better way to do this, the original neovim code action implementation do the same thing so...
