### ISSUE TITLE
Can you help me get this running? 

### ISSUE THREAD

**Issue by unphased** [luckasRanarison/clear-action.nvim#21]
Using Lazy here, and I've tried: 

```
{
  "luckasRanarison/clear-action.nvim",
  opts = {
        silent = false,
        mappings = {
          code_action = '<leader>a',
        }
      }
}
```
as well as

```
  {
    "luckasRanarison/clear-action.nvim",
    config = function ()
      require('clear-action').setup({
        silent = false,
        mappings = {
          code_action = '<leader>a',
        }
      })
    end
  }
```

And neither change any behavior or add a `<leader>a` bind.

**Comment by unphased** [comment]
OK so none of the bindings appear to be set, but i did get a virtual text lightbulb appear (then quickly covered up by my git blame, but that is ok I'll deal with that later). fwiw.

**Comment by luckasRanarison** [comment]
I broke the string keymaps with my last commit but it should be fixed now, about the git blame maybe I could make the extmark priority configurable, currently it's set to 200, I don't know what value git blame is using.

**Comment by unphased** [comment]
Thanks! I'll play with it. docs seem sufficient. will be awesome to be able to see available CAs without crossing the fingers and trying to trigger one every time.

**Comment by mawkler** [comment]
I'm having the same issue now using the config above. No light bulb or mapping created. The language server is attached properly because I'm seeing diagnostics.
