### ISSUE TITLE
always seem to get some strange count of code actions

### ISSUE THREAD

**Issue by unphased** [luckasRanarison/clear-action.nvim#22]
In this example of my plugins lua file it seems like the count is 4 times higher than it should be.

https://github.com/luckasRanarison/clear-action.nvim/assets/1542910/37d5fe4b-9ff7-442c-8398-01cb2f82576b

**Comment by unphased** [comment]
And here is it showing 4 when it should be 5: 
<img width="470" alt="image" src="https://github.com/luckasRanarison/clear-action.nvim/assets/1542910/43b49696-f838-41a9-99fb-6a9a4df55c9b">

**Comment by unphased** [comment]
also there is some background color issue with text in the menu but i may be able to ferret that one out

**Comment by luckasRanarison** [comment]
The counting issue should be fixed now, it looks like I broke a lot of stuff when implementing new features... Thanks for the report!

> also there is some background color issue with text in the menu but i may be able to ferret that one out
You can just change the plugin highlight group color, currently it's just linked to some built-in highlight groups. All the highlight groups start with `CodeAction`.

**Comment by unphased** [comment]
Perfect, thank you!!!

**Comment by unphased** [comment]
Still having an issue in typescript. Though it's fixed in lua. 
<img width="624" alt="image" src="https://github.com/luckasRanarison/clear-action.nvim/assets/1542910/fb637a03-8935-4b11-bf61-7d4faf305c13">

**Comment by unphased** [comment]
and another shameless request -- can we exclude q from being used as a choice key and bind it to close the popup?

**Comment by unphased** [comment]
I'm also experiencing spurious errors like this 

```
code action: <semantic> TypeScript Server Error (5.2.2)
BADCLIENT: Bad error code, 7044 not found in range 6695..6695 (found: false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, f
alse, false); could have caused this error:
Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isParameter'.
Error: BADCLIENT: Bad error code, 7044 not found in range 6695..6695 (found: false, false, false, false, false, false, false, false, false, false, false, false, false, false, f
alse, false, false); could have caused this error:
Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isParameter'.
    at cast (/Users/slu/entropy-dynamics/nucleus/instrumenter/node_modules/typescript/lib/tsserver.js:3484:16)
    at doChange32 (/Users/slu/entropy-dynamics/nucleus/instrumenter/node_modules/typescript/lib/tsserver.js:154315:23)
    at /Users/slu/entropy-dynamics/nucleus/instrumenter/node_modules/typescript/lib/tsserver.js:154199:21
    at _ChangeTracker.with (/Users/slu/entropy-dynamics/nucleus/instrumenter/node_modules/typescript/lib/tsserver.js:168176:5)
    at Object.getCodeActions (/Users/slu/entropy-dynamics/nucleus/instrumenter/node_modules/typescript/lib/tsserver.js:154198:62)
    at /Users/slu/entropy-dynamics/nucleus/instrumenter/node_modules/typescript/lib/tsserver.js:147054:46
    at flatMap (/Users/slu/entropy-dynamics/nucleus/instrumenter/node_modules/typescript/lib/tsserver.js:2600:17)
    at Object.getFixes (/Users/slu/entropy-dynamics/nucleus/instrumenter/node_modules/typescript/lib/tsserver.js:147054:10)
    at /Users/slu/entropy-dynamics/nucleus/instrumenter/node_modules/typescript/lib/tsserver.js:144396:33
    at flatMap (/Users/slu/entropy-dynamics/nucleus/instrumenter/node_modules/typescript/lib/tsserver.js:2600:17)
    at Object.getCodeFixesAtPosition (/Users/slu/entropy-dynamics/nucleus/instrumenter/node_modules/typescript/lib/tsserver.js:144394:12)
    at IpcIOSession.getCodeFixes (/Users/slu/entropy-dynamics/nucleus/instrumenter/node_modules/typescript/lib/tsserver.js:184536:50)
    at getCodeFixes (/Users/slu/entropy-dynamics/nucleus/instrumenter/node_modules/typescript/lib/tsserver.js:182652:43)
    at /Users/slu/entropy-dynamics/nucleus/instrumenter/node_modules/typescript/lib/tsserver.js:184838:69
    at IpcIOSession.executeWithRequestId (/Users/slu/entropy-dynamics/nucleus/instrumenter/node_modules/typescript/lib/tsserver.js:184830:14)
    at IpcIOSession.executeCommand (/Users/slu/entropy-dynamics/nucleus/instrumenter/node_modules/typescript/lib/tsserver.js:184838:29)
    at IpcIOSession.onMessage (/Users/slu/entropy-dynamics/nucleus/instrumenter/node_modules/typescript/lib/tsserver.js:184880:51)
    at process.<anonymous> (/Users/slu/entropy-dynamics/nucleus/instrumenter/node_modules/typescript/lib/tsserver.js:186461:14)
    at process.emit (node:events:519:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Press ENTER or type command to continue
```

while scrolling around in my ts code. It makes sense we gotta continuously query the LSP for CAs... Hmm...

**Comment by luckasRanarison** [comment]
> Still having an issue in typescript. Though it's fixed in lua. 

Could you provide detailed step to reproduce, it's working fine for me when trying to replicate your code.

> and another shameless request -- can we exclude q from being used as a choice key and bind it to close the popup? 

Could you make a separate issue for that. But I don't want to introduce some special handling for a given character. Closing the popup if the window is not focused would make more sense and easier to implement.

> I'm also experiencing spurious errors like this

This is a mainstream issue, that's why the `silent` option was provided to dismiss errors notifications like this.

**Comment by luckasRanarison** [comment]
Sending code action is relatively cheap, it won't affect the performance of the server. That error is just caused by some bad error handling on malformed nodes from the server.

**Comment by unphased** [comment]
hmm ok i will try some more. Soooo I tried to go without your plugin for a bit, but using telescope for code actions seems nearly impossible to configure the popup to not be humongous. I'm also looking to move on from telescope in general. Your popup is nice.

**Comment by unphased** [comment]
oh ok i think i know why. i feel like the reason it shows one lightbulb when i have 4 is because 1 is provided by null-ls (always, it's the git blame one), and the other LSP for the language is providing the rest. Maybe we're not grabbing all from all lsp's?

**Comment by luckasRanarison** [comment]
> oh ok i think i know why. i feel like the reason it shows one lightbulb when i have 4 is because 1 is provided by null-ls (always, it's the git blame one), and the other LSP for the language is providing the rest. Maybe we're not grabbing all from all lsp's?

I think you're correct, I just realized that the counting is per client and I haven't thought about the possibility to have multiple code action providers at the time. 

This is really tricky though, because the requests are sent asynchronously.

**Comment by unphased** [comment]
can you point me at the relevant code? I can probably contribute something for this.

**Comment by luckasRanarison** [comment]
> https://github.com/luckasRanarison/clear-action.nvim/blob/master/lua/clear-action/signs.lua#L73-L73

To solve this we could change this to `vim.lsp.buf_request_all` but the problem is this function doesn't return the context of the request unlike `vim.lsp.buf_request` so the easiest solution would be passing the context manually.

**Comment by unphased** [comment]
Will the system call `on_result` for us as many times as there are LSPs that provide code action results? Or is it less simple than that?

**Comment by unphased** [comment]
> To solve this we could change this to `vim.lsp.buf_request_all` but the problem is this function doesn't return the context of the request unlike `vim.lsp.buf_request` so the easiest solution would be passing the context manually.

To clarify, I didn't get it the first time but I now understand you seem to be suggesting to use buf_request_all and we just need to find a way to pass the bufnr and position offset (`context.params.range.start.line`) to the async response handler.

**Comment by unphased** [comment]
Cool, i should be 90% of the way there. reconciling the different structure of the buf_request_all response with existing on_result code now.

**Comment by unphased** [comment]
The main thing now is the label_fmt interface ... I could flatten the action responses which are grouped by client_id (lsp id) to maintain the same interface or I could preserve it, but it would make label_fmt more complex. I'm leaning toward the latter because it's not clear flattening the list is extra work worth doing.

**Comment by luckasRanarison** [comment]
> - preview of what change the code action would apply... i didn't know we got access to this immediately! As an example, we can show an indicator character if the action would modify anything more than the current file!

That's an interesting idea, there are already some code action preview plugins out there and it's not that hard to implement, but I don't really know where to place it... If we were using a telescope preview or anything using some key navigations I'd make sense to have a preview but it's not obvious in our case.

> OK i would love to roll my #25 concept of bringing in the name of the lsp client into the actions list to send to label_fmt, while flattening the list of actions. So I will assemble a flattened list of actions.

We could also append to client id to each action and get the name after

**Comment by unphased** [comment]
Yeah i read enough of the code to know you went ahead and built a custom popup window and I love that you made it very compact and also the dynamic keybind aliases to trigger them is a super nice touch. Previews wouldn't work in this context since it's just a single action, and tell ya what I'd love to preserve this rather than making it another interactive menu to interact extensively with -- maybe if we came up with a way condense a very compact "preview" of what's involved in the action (number of files changed, possibly number of lines removed/added like git diff stat or something?) we can just optionally shove that into the label?

> We could also append to client id to each action and get the name after

well what do you think about #28 because i added the client name because you preserved the client_id far enough for me to be able to do that. It isn't visible for label_fmt but I'm not sure that's important. In fact I am already finding that the way the extmark currently renders tends to cover up buffer contents, which to me is a no-no... I'd wanna address that next since showing some context on what the codeactions available are in the virt text is pretty important. Anyway, what do you think?

**Comment by unphased** [comment]
#26
