### ISSUE TITLE
enhancement: allow max length for label, prevent label from covering up buffer content

### ISSUE THREAD

**Issue by unphased** [luckasRanarison/clear-action.nvim#23]
The labels are often long and they actually cover up the buffer. Both of these features should be provided in order for show_label to be worth using. And if we dont show the label then all we can get are the counts which is not really enough to justify using.  

Example

<img width="651" alt="image" src="https://github.com/luckasRanarison/clear-action.nvim/assets/1542910/749bf9ab-98d8-4956-863c-ab2ca1b8b9de">

**Comment by luckasRanarison** [comment]
There's already the `label_fmt` option, you could do something like this:

```lua
{
  sings = {
    label_fmt = function(actions)
      local title = actions[1].title
      if #title > 20 then
        return title:sub(1, 20) .. "..." -- truncating
      else
        return title
      end
    end
  }
}
```
