### ISSUE TITLE
Error: Invalid buffer id: 869

### ISSUE THREAD

**Issue by mawkler** [luckasRanarison/clear-action.nvim#29]
Sometimes when entering a new buffer I get the following error message:

```
Error executing vim.schedule lua callback: ...e/nvim/lazy/clear-action.nvim/lua/clear-action/signs.lua:67: Invalid buffer id: 869
stack traceback:
	[C]: in function 'nvim_buf_set_extmark'
	...e/nvim/lazy/clear-action.nvim/lua/clear-action/signs.lua:67: in function 'on_result'
	...e/nvim/lazy/clear-action.nvim/lua/clear-action/utils.lua:38: in function 'handler'
	/usr/share/nvim/runtime/lua/vim/lsp.lua:1887: in function 'handler'
	/usr/share/nvim/runtime/lua/vim/lsp.lua:1185: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

Note that I don't actually call `vim.lsp.buf.code_action`. I get the error immediately after entering (some) new buffers.

I have quite a large config, so I haven't tried to debug it further yet. Do you have any idea what could be causing the issue?

**Comment by luckasRanarison** [comment]
Could you see if it's fixed now?

**Comment by mawkler** [comment]
@luckasRanarison I haven't encountered the error since upgrading, so I think that you solved the issue for me. Thank you very much!
