### ISSUE TITLE
Add { nowait = true } for keymaps setting

### ISSUE THREAD

**Issue by KostkaBrukowa** [luckasRanarison/clear-action.nvim#5]
Hello!
I've been using your plugin and I've found out that when I want to use code action from popup sometimes it's slower than older solution I've used. I think it's because in this [piece of code](https://github.com/luckasRanarison/clear-action.nvim/blob/master/lua/clear-action/popup.lua#L98-L101)
when you are setting for example `vim.keymap.set("n", 'd', ...` and you press `d` then nvim waits for next letters for maybe some different keymap (like `diw`). Adding ` { nowait = true }` for `vim.keymap.set` solves this issue.

**Comment by luckasRanarison** [comment]
Thanks again, I really appreciate your remarks. Btw you can also make a PR.
