### ISSUE TITLE
Error when using `eslint_d` code action

### ISSUE THREAD

**Issue by KostkaBrukowa** [luckasRanarison/clear-action.nvim#6]
Hey!
I'm using `eslint_d` for my TS linting and when I want to pick a code action I'm getting this error:
```
[actions.lua:19] -- action_tuple: { 1, {
    arguments = {
      title = "Disable ESLint rule @typescript-eslint/explicit-function-return-type for the entire file"
    },
    command = "NULL_LS_CODE_ACTION",
    title = "Disable ESLint rule @typescript-eslint/explicit-function-return-type for the entire file"
  } }
E5108: Error executing lua: ...acker/start/clear-action.nvim/lua/clear-action/utils.lua:8: attempt to call field '_exec_cmd' (a nil value)
stack traceback:
	...acker/start/clear-action.nvim/lua/clear-action/utils.lua:8: in function 'apply_action'
	...acker/start/clear-action.nvim/lua/clear-action/utils.lua:43: in function 'handle_action'
	...ker/start/clear-action.nvim/lua/clear-action/actions.lua:27: in function 'on_select'
	...acker/start/clear-action.nvim/lua/clear-action/popup.lua:116: in function <...acker/start/clear-action.nvim/lua/clear-action/popup.lua:115>
```

**Comment by luckasRanarison** [comment]
Perhaps `_exec_cmd` was added in the nightly version, I'll check the implementation in the previous versions for backward compabitility.

**Comment by KostkaBrukowa** [comment]
For your information I'm running 'nvim 0.9.2' and this only happens with eslint_d actions, and they come from 'null-ls' so maybe there is a problem with null-ls itself?

**Comment by luckasRanarison** [comment]
> For your information I'm running 'nvim 0.9.2' and this only happens with eslint_d actions, and they come from 'null-ls' so maybe there is a problem with null-ls itself?

I've checked the default `code_action()` implementation in 0.9.2 and `_exec_cmd` didn't exist at the time. Can you try if it's solved in this [branch](https://github.com/luckasranarison/clear-action.nvim/tree/action-cmd) I haven't tried yet if it also works in the nightly version.

**Comment by KostkaBrukowa** [comment]
Hey! I've checked and it fine now. Thanks for the fix!!

**Comment by luckasRanarison** [comment]
It also works with the nightly version so I'll use this implementation for backward compability.
