### ISSUE TITLE
Suggestion: other letter picking in code action popup

### ISSUE THREAD

**Issue by KostkaBrukowa** [luckasRanarison/clear-action.nvim#7]
Let's say you have three code actions:
- A code action
- A other code action
- B code action

In this order. Your algorithm for picking right letter will do something like this
```
a A code action
b A other code action
c B code action 
```
I think that it would be nicer for it to maximize how many actions will have the same first letter in popup, so I would like it to show:
```
a A code action
c A other code action
b B code action 
```
It could be easily done by first choosing first letter for all of the code actions and then choose for those that were already taken. Something like this

```lua
local function create_labels(action_tuples)
  local labels = {}
  local used = {}
  local fallback = "a"

  -- first pick first letters
  for _, value in pairs(action_tuples) do
    local title = value[2].title
    local first_letter = title:sub(1, 1):lower()

    if not used[first_letter] then
      used[first_letter] = true
      labels[title] = first_letter
    end
  end
  -- then look for fallback for the rest
  for _, value in pairs(action_tuples) do
    local title = value[2].title
    if not labels[title] then
      while used[fallback] do
        fallback = string.char(fallback:byte() + 1)
      end
      if fallback:byte() > 122 then fallback = "A" end
      used[fallback] = true
      labels[title] = fallback
    end
  end

  return labels
end

```
What do you think about it?
Btw. you are writing really great code. It's really easy to understand and read!

**Comment by luckasRanarison** [comment]
Thanks for the remark :) You're indeed correct.
